// THIS FILE IS AUTOGENERATED BY CUGOGEN
package main

type Dummy struct {
	Name string
	Type string
}
type Metadata struct {
	Name        string
	Description string
	Dumm        Dummy
}
type RootStruct struct {
	ApiVersion string
	Kind       string
	Metadata   Metadata
	Spec       struct {
		Components []struct {
			Name string
			Type string
		}
	}
}
